---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: radarr
    version: 3.0.2
  values:
    image:
      repository: linuxserver/radarr
      tag: 3.0.0.2704-ls10
    timezone: "America/New_York"
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    persistence:
      #
      # config needs to be local-path, see https://github.com/Sonarr/Sonarr/issues/1886
      #
      config:
        enabled: true
        storageClass: "local-path"
      downloads:
        enabled: false
      movies:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: /media
          readOnly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    #
    # @CHANGEME - Update the hostname to the node you want this deployed to
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k3s-10-128-128-24
  valueFileSecrets:
  - name: "radarr-helm-values"